import type { Metadata } from "next";
import HorizontalNavbar from "@/components/HorizontalNavbar";
import VerticalNavbar from "@/components/VerticalNavbar";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="h-full antialiased">
            <body className="min-h-full">
                <div className="min-h-screen md:flex">
                    <div className="md:hidden">
                        <HorizontalNavbar />
                    </div>
                    <aside className="hidden shrink-0 basis-1/5 md:block">
                        <VerticalNavbar />
                    </aside>
                    <main className="flex-1 px-4 md:basis-4/5 md:px-0 md:pl-[10vw]">
                        {children}
                    </main>
                </div>
            </body>
        </html>
    );
}
