import type { Metadata } from "next";
import VerticalNavbar from "@/components/VerticalNavbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full">
        <div className="flex min-h-screen">
          <aside className="basis-1/5 shrink-0">
            <VerticalNavbar />
          </aside>
          <main className="basis-4/5 flex-1">{children}</main>
        </div>
      </body>
    </html>
  );
}
