import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import VerticalNavbar from "@/components/VerticalNavbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full">
        <div className="flex min-h-screen">
          <aside className="basis-1/5 shrink-0">
            <VerticalNavbar />
          </aside>
          <main className="basis-4/5 flex-1">{children}</main>
        </div>
      </body>
    </html>
  );
}
